### ISSUE TITLE
ShrubAPI#generateRandomNumber is wrong

### ISSUE THREAD

**Issue by nickrobson** [InitializeSahib/Shrub#1]
It simply returns a number in 0..(max-min+1).

**Comment by nickrobson** [comment]
Also, don't extend Random..

**Comment by InitializeSahib** [comment]
ok

**Comment by InitializeSahib** [comment]
Fixed in 3.0.
Also, max - min + 1 is the only solution I have found.
I may use a more complex way, but expect that in 4.0.

**Comment by nickrobson** [comment]
min + random.nextInt(max-min+1) yields the correct range.

**Comment by InitializeSahib** [comment]
Ah ok. Thanks.
